-- ============================================================
-- E-commerce Customer Analytics - SQL Queries
-- ============================================================
-- This file contains SQL queries to answer the core business
-- questions defined in the project (Revenue, Customers, Products,
-- RFM Segmentation).
--
-- Tables used:
--   customers(customer_id, signup_date, ...)
--   orders(order_id, customer_id, order_date, order_status, ...)
--   order_items(order_id, product_id, quantity, price)
--   products(product_id, category, ...)
--   payments(order_id, payment_value, payment_type)
--   reviews(order_id, review_score)
-- ============================================================


-- ------------------------------------------------------------
-- 1. REVENUE
-- ------------------------------------------------------------

-- 1.1 Monthly Sales
-- Total revenue generated per month
SELECT
    DATE_TRUNC('month', o.order_date) AS month,
    SUM(oi.quantity * oi.price) AS monthly_revenue
FROM orders o
JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY 1
ORDER BY 1;


-- 1.2 Year-over-Year (YoY) Growth
-- Compares each year's revenue to the previous year
WITH yearly_revenue AS (
    SELECT
        EXTRACT(YEAR FROM o.order_date) AS year,
        SUM(oi.quantity * oi.price) AS revenue
    FROM orders o
    JOIN order_items oi ON o.order_id = oi.order_id
    GROUP BY 1
)
SELECT
    year,
    revenue,
    LAG(revenue) OVER (ORDER BY year) AS prev_year_revenue,
    ROUND(
        (revenue - LAG(revenue) OVER (ORDER BY year))
        / LAG(revenue) OVER (ORDER BY year) * 100, 2
    ) AS yoy_growth_percent
FROM yearly_revenue
ORDER BY year;


-- 1.3 Average Order Value (AOV)
-- Total revenue divided by total number of orders
SELECT
    ROUND(SUM(oi.quantity * oi.price) / COUNT(DISTINCT o.order_id), 2) AS avg_order_value
FROM orders o
JOIN order_items oi ON o.order_id = oi.order_id;


-- ------------------------------------------------------------
-- 2. CUSTOMERS
-- ------------------------------------------------------------

-- 2.1 Repeat Purchase Rate
-- % of customers who placed more than one order
SELECT
    ROUND(
        SUM(CASE WHEN order_count > 1 THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2
    ) AS repeat_purchase_rate_percent
FROM (
    SELECT customer_id, COUNT(DISTINCT order_id) AS order_count
    FROM orders
    GROUP BY customer_id
) t;


-- 2.2 Customer Lifetime Value (CLV)
-- Total revenue generated by each customer (simple historical CLV)
SELECT
    c.customer_id,
    SUM(oi.quantity * oi.price) AS lifetime_value
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY c.customer_id
ORDER BY lifetime_value DESC;


-- 2.3 New vs Returning Customers (per month)
-- Classifies each customer's orders as "New" (first order) or "Returning"
WITH first_orders AS (
    SELECT
        customer_id,
        MIN(order_date) AS first_order_date
    FROM orders
    GROUP BY customer_id
)
SELECT
    DATE_TRUNC('month', o.order_date) AS month,
    CASE
        WHEN DATE_TRUNC('month', o.order_date) = DATE_TRUNC('month', f.first_order_date)
        THEN 'New'
        ELSE 'Returning'
    END AS customer_type,
    COUNT(DISTINCT o.customer_id) AS customer_count
FROM orders o
JOIN first_orders f ON o.customer_id = f.customer_id
GROUP BY 1, 2
ORDER BY 1, 2;


-- 2.4 Top 10 Customers by Revenue
SELECT
    c.customer_id,
    SUM(oi.quantity * oi.price) AS total_spent
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY c.customer_id
ORDER BY total_spent DESC
LIMIT 10;


-- ------------------------------------------------------------
-- 3. PRODUCTS
-- ------------------------------------------------------------

-- 3.1 Best-Selling Categories (by revenue)
SELECT
    p.category,
    SUM(oi.quantity * oi.price) AS category_revenue,
    SUM(oi.quantity) AS units_sold
FROM order_items oi
JOIN products p ON oi.product_id = p.product_id
GROUP BY p.category
ORDER BY category_revenue DESC;


-- 3.2 Low-Performing Products (bottom 10 by revenue)
SELECT
    p.product_id,
    p.category,
    SUM(oi.quantity * oi.price) AS product_revenue,
    SUM(oi.quantity) AS units_sold
FROM order_items oi
JOIN products p ON oi.product_id = p.product_id
GROUP BY p.product_id, p.category
ORDER BY product_revenue ASC
LIMIT 10;


-- 3.3 Most Profitable Products (top 10 by revenue)
SELECT
    p.product_id,
    p.category,
    SUM(oi.quantity * oi.price) AS product_revenue,
    SUM(oi.quantity) AS units_sold
FROM order_items oi
JOIN products p ON oi.product_id = p.product_id
GROUP BY p.product_id, p.category
ORDER BY product_revenue DESC
LIMIT 10;


-- ------------------------------------------------------------
-- 4. RFM ANALYSIS (Recency, Frequency, Monetary)
-- ------------------------------------------------------------

-- 4.1 Raw RFM values per customer
-- Recency  = days since last order (relative to most recent order date in data)
-- Frequency = number of distinct orders
-- Monetary  = total amount spent
WITH rfm_raw AS (
    SELECT
        o.customer_id,
        DATE_PART('day', (SELECT MAX(order_date) FROM orders) - MAX(o.order_date)) AS recency,
        COUNT(DISTINCT o.order_id) AS frequency,
        SUM(oi.quantity * oi.price) AS monetary
    FROM orders o
    JOIN order_items oi ON o.order_id = oi.order_id
    GROUP BY o.customer_id
)
SELECT * FROM rfm_raw
ORDER BY monetary DESC;


-- 4.2 RFM Scoring (1-5 using NTILE quantiles)
-- Higher score = better (5 = best recency/frequency/monetary)
WITH rfm_raw AS (
    SELECT
        o.customer_id,
        DATE_PART('day', (SELECT MAX(order_date) FROM orders) - MAX(o.order_date)) AS recency,
        COUNT(DISTINCT o.order_id) AS frequency,
        SUM(oi.quantity * oi.price) AS monetary
    FROM orders o
    JOIN order_items oi ON o.order_id = oi.order_id
    GROUP BY o.customer_id
)
SELECT
    customer_id,
    recency,
    frequency,
    monetary,
    -- Recency: lower days = higher score, so reverse the NTILE order
    (6 - NTILE(5) OVER (ORDER BY recency)) AS r_score,
    NTILE(5) OVER (ORDER BY frequency)     AS f_score,
    NTILE(5) OVER (ORDER BY monetary)      AS m_score
FROM rfm_raw
ORDER BY customer_id;


-- 4.3 Customer Segmentation based on RFM scores
-- Wraps the scoring query above and classifies customers into segments
WITH rfm_raw AS (
    SELECT
        o.customer_id,
        DATE_PART('day', (SELECT MAX(order_date) FROM orders) - MAX(o.order_date)) AS recency,
        COUNT(DISTINCT o.order_id) AS frequency,
        SUM(oi.quantity * oi.price) AS monetary
    FROM orders o
    JOIN order_items oi ON o.order_id = oi.order_id
    GROUP BY o.customer_id
),
rfm_scored AS (
    SELECT
        customer_id,
        (6 - NTILE(5) OVER (ORDER BY recency)) AS r_score,
        NTILE(5) OVER (ORDER BY frequency)     AS f_score,
        NTILE(5) OVER (ORDER BY monetary)      AS m_score
    FROM rfm_raw
)
SELECT
    customer_id,
    r_score, f_score, m_score,
    CASE
        WHEN r_score >= 4 AND f_score >= 4 AND m_score >= 4 THEN 'Champions'
        WHEN r_score >= 3 AND f_score >= 3                  THEN 'Loyal Customers'
        WHEN r_score >= 4 AND f_score <= 2                  THEN 'Potential Loyalists'
        WHEN r_score <= 2 AND f_score >= 3                  THEN 'At Risk'
        WHEN r_score <= 2 AND f_score <= 2                  THEN 'Lost Customers'
        ELSE 'Others'
    END AS segment
FROM rfm_scored
ORDER BY customer_id;
